# c:\Users\Robi\Desktop\Shega Skin Studio\docker-compose.yml

services:
  # 1. Frontend Service (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # 2. Backend Service (Node.js)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/shega_skin_studio
      - PORT=5000
      - JWT_SECRET=12345678 # ይህንን በራስዎ ሚስጥራዊ ቁልፍ ይቀይሩ
      - SUPER_ADMIN_EMAIL=baby@example.com
      - SUPER_ADMIN_PASSWORD=shega123
    depends_on:
      - mongo

  # 3. Database Service (MongoDB)
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
